[package]
name = "seed-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Parser for Seed documents"

[dependencies]
seed-core.workspace = true
nom.workspace = true
thiserror.workspace = true
